name: PR Tests
on:
  pull_request: {}
permissions: read-all
jobs:
  lint:
    name: Lint
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Lint files
        uses: go-orb/dagger-for-github@main
        with:
          version: "latest"
          verb: call
          args: lint --root=. logs
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
  test:
    name: Unit Tests
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Lint files
        uses: go-orb/dagger-for-github@main
        with:
          version: "latest"
          verb: call
          args: test --root=. logs
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
